spring:
  application:
    name: temperature-finder

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${CONTEXT_PATH:/temperature/}

app:
  coordinates-api: http://localhost:8080/address/geocode
  openweather-api: https://api.openweathermap.org/data/2.5/weather
  openweather-key: ${API_KEY}