name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.7+7'
          distribution: 'temurin'
          cache: maven
          
      - name: Exec maven tests and build
        run: mvn package

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: |
            weversonlemos/temperature-finder:v1
            weversonlemos/temperature-finder:latest
